spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_DATABASE:mysql}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  flyway:
    default-schema: mysql
    schemas: mysql
    baseline-on-migrate: true